# Generated by Django 2.1.2 on 2018-10-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Algo name')),
                ('signal', models.CharField(max_length=500, verbose_name='Signal')),
                ('ticker', models.CharField(max_length=50, verbose_name='Ticker')),
                ('trade', models.CharField(max_length=500, verbose_name='Trade')),
                ('positions', models.TextField(blank=True, null=True, verbose_name='Positions')),
                ('pnl', models.TextField(blank=True, null=True, verbose_name='Average PnL')),
            ],
        ),
    ]
